### ISSUE TITLE
Birdseye report broken

### ISSUE THREAD

**Issue by alexef** [cortexapps/backstage-plugin#187]
Started in 2.11.2 but somehow 2.10.2 and 2.9.2 are also affected. What happened with the release process of https://github.com/cortexapps/backstage-plugin/pull/169?

```
Error
TypeError

Message
Cannot read properties of undefined (reading 'codeTag')

Stack Trace
TypeError: Cannot read properties of undefined (reading 'codeTag')
    at https://stack.gygservice.com/static/3767.5bd872da.chunk.js:2:44521
    at Array.map (<anonymous>)
    at https://stack.gygservice.com/static/3767.5bd872da.chunk.js:2:44506
    at Array.forEach (<anonymous>)
    at https://stack.gygservice.com/static/3767.5bd872da.chunk.js:2:44446
    at Object.ss [as useMemo] (https://stack.gygservice.com/static/module-react-dom.383a33ee.js:14:21288)
    at g.useMemo (https://stack.gygservice.com/static/vendor.80f78496.js:148:6162)
    at ic (https://stack.gygservice.com/static/3767.5bd872da.chunk.js:2:44295)
    at ki (https://stack.gygservice.com/static/module-react-dom.383a33ee.js:14:16959)
    at Mi (https://stack.gygservice.com/static/module-react-dom.383a33ee.js:16:3147)
```
<img width="983" alt="Screenshot 2024-06-24 at 14 37 23" src="https://github.com/cortexapps/backstage-plugin/assets/346576/ed83c0bc-4d96-400a-94f1-6c32fc29d4fa">

**Comment by alexef** [comment]
Fixed in: https://github.com/cortexapps/backstage-plugin/pull/189
